all:
	make -C mylog/
	make -C MyException/
	make -C structmask/
	make -C algo/
	make -C creat_sign/
	make -C fileblock/
	make -C diskv/
	make -C filelinkblock/
	make -C memblocks/
	make -C postinglist/
